version: "3"

services:
  torrent_backend_service:
    container_name: torrent-backend-service
    image: satanicus1991/torrent-backend-service:latest
    network_mode: host
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_USERNAME=${SERVER_USERNAME}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
    restart: unless-stopped
