version: "3"

services:
  torrent_backend_service:
    container_name: torrent-backend-service
    image: satanicus1991/torrent-backend-service:latest
    ports:
      - "3001:3001/tcp"
    restart: unless-stopped